# Generated by Django 4.1.7 on 2023-03-11 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='personal_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('mobile_no', models.CharField(max_length=255)),
                ('charges', models.IntegerField(max_length=100)),
                ('available', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'personal_info',
            },
        ),
    ]
