# Generated by Django 4.1.7 on 2023-03-11 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='personal_info',
        ),
    ]
