# Generated by Django 4.1.7 on 2023-03-11 22:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('guide', '0004_delete_personal_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registrations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('uuid', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Personal_Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=20)),
                ('charges', models.IntegerField(default=200)),
                ('available', models.BooleanField(default=True)),
                ('uuid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guide.registrations')),
            ],
        ),
        migrations.CreateModel(
            name='guide_specilization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spceilization_id', models.CharField(max_length=100)),
                ('uuid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guide.registrations')),
            ],
        ),
        migrations.CreateModel(
            name='guide_language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_id', models.CharField(max_length=100)),
                ('uuid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guide.registrations')),
            ],
        ),
        migrations.CreateModel(
            name='guide_city',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_id', models.CharField(max_length=100)),
                ('uuid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guide.registrations')),
            ],
        ),
    ]
